testing sourceforge

diff --git a/.github/workflows/mirror.yml b/.github/workflows/mirror.yml
--- a/.github/workflows/mirror.yml
+++ b/.github/workflows/mirror.yml
@@ -43,4 +43,7 @@ jobs:
           echo "Pushing to SourceForge..."
           git push --mirror https://${{ secrets.SF_USER }}:${{ secrets.SF_TOKEN }}@git.code.sf.net/p/xlade/code || echo "SourceForge push failed"
 
+          echo "Pushing to SourceForge..."
+          git push --mirror https://${{ secrets.SF_USER }}:${{ secrets.SF_TOKEN }}@sourceforge.net/lakshitsinghbishttm/xlade || echo "SourceForge push failed"
+
           echo "All mirror attempts completed."
